### ISSUE TITLE
指定轮廓 SVG 时报错

### ISSUE THREAD

**Issue by Justineo** [ecomfe/echarts-liquidfill#10]
经测试只发生于自定义 SVG 轮廓且 ECharts 版本 ≥ 3.4.0 （依赖的 zrender 版本从 3.2.2 切换为 3.3.0 了，估计是 zrender 3.3.0 造成的）时。

```
TypeError: path.setData is not a function
```

位置在 `zrender/lib/tool/path.js` 第 334 行。

**Comment by Mignon-han** [comment]
升级了echarts3.5.3 同样遇到了这个`showstopper `

**Comment by Ovilia** [comment]
是的，这是 zrender 更新引起的，将在下个版本中修复

**Comment by Ovilia** [comment]
https://github.com/ecomfe/zrender/commit/38d77a7aed8fe04f7cd7093fdc8c0a7977780323 已修复
