### ISSUE TITLE
通过getZr().on拿到的事件 怎么判断是属于水波球的

### ISSUE THREAD

**Issue by wxj0102** [ecomfe/echarts-liquidfill#101]
```js
chart.getZr().on('click', function() {
       // 如何根据arguments 判断我点了什么
       console.log(arguments);
});
```

**Comment by Ovilia** [comment]
```js
chart.on('click', function() {
       console.log(arguments);
});
```
这样获取到的点击事件是来自系列的，可能根据 type 等信息判断是否是水球图

**Comment by wxj0102** [comment]
但是这样添加的事件, 在点击水波球水波以外的地方是不响应的. 
我看文档上说要通过getZr()才能响应事件, 但是又无法区分我点了谁.

**Comment by Ovilia** [comment]
的确是只有点水波才有事件的，就像柱状图点柱子、折线图点数据点。你想要点哪里获得事件呢？

**Comment by wxj0102** [comment]
我在一个图表中加了好多水波球, 我希望可以通过点击整个水波球, 知道事件是哪个水波球触发的.

**Comment by Ovilia** [comment]
用你最初的方法，应该可以获取到坐标，然后再判断？

**Comment by wxj0102** [comment]
我试了试, 不行啊, 坐标转不出来,不知道是不是我操作有问题.
但是我在event.target.style里面发现了一些可以作为标识的样式, 例如当e.target.style.fill为某个值的时候, 就是水波球触发的.
