### ISSUE TITLE
echarts/lib/visual/dataColor not found in echarts@5.0.0

### ISSUE THREAD

**Issue by cheqianxiao** [ecomfe/echarts-liquidfill#119]
with echarts@5.0.0-rc.1 :

![image](https://user-images.githubusercontent.com/16025751/100689901-5b187900-33c0-11eb-91ca-42ba87b2b8f3.png)

**Comment by yx928** [comment]
降级echarts的版本到4.x

**Comment by webxiaonew** [comment]
同问

**Comment by webxiaonew** [comment]
> 降级echarts的版本到4.x

谢谢，搞定了

**Comment by yx928** [comment]
不用，一起加油



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "webxiaonew"<notifications@github.com&gt;; 
发送时间: 2020年12月19日(星期六) 中午12:28
收件人: "ecomfe/echarts-liquidfill"<echarts-liquidfill@noreply.github.com&gt;; 
抄送: "不是天使"<773258675@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ecomfe/echarts-liquidfill] echarts/lib/visual/dataColor not found in echarts@5.0.0 (#119)





  
降级echarts的版本到4.x
  
谢谢，搞定了

**Comment by pissang** [comment]
Just published 3.0 to compatible with echarts@5.0.1
