### ISSUE TITLE
with echarts@5.0.0, completeDimensions is not a function 

### ISSUE THREAD

**Issue by cheqianxiao** [ecomfe/echarts-liquidfill#120]
![image](https://user-images.githubusercontent.com/16025751/100692782-8605cb80-33c6-11eb-8892-e6b37fd17253.png)

```js
var completeDimensions = require('echarts/lib/data/helper/completeDimensions')
```
related with https://github.com/microsoft/TypeScript/issues/2719 , should we add `.default` after require ? (but not compitable with echarts@4.x  )

**Comment by pissang** [comment]
水球图插件后续会升级到支持 echarts 5.0

**Comment by gaooooo** [comment]
> 水球图插件后续会升级到支持 echarts 5.0

这个预计什么时间更新呢？ 目前升级阻塞了。

**Comment by DoonPort0422** [comment]
同问

谢谢

**Comment by q604265262** [comment]
大概什么时间支持到5.0？

**Comment by q604265262** [comment]
您好  因为只能用html引入，但是现在依然报**parsePercent is not a function**错误
![QQ截图20210108103731](https://user-images.githubusercontent.com/32191557/103967761-9f581f80-519d-11eb-9d98-90dd97e0dcc5.png)

**Comment by pissang** [comment]
@q604265262 还没有发布，下周等 echarts 5.0.1 发布后一起更新

**Comment by q604265262** [comment]
> @ q604265262还没有发布，下周等echarts 5.0.1发布后一起更新

好的 非常感谢

**Comment by q604265262** [comment]
> @q604265262 还没有发布，下周等 echarts 5.0.1 发布后一起更新

您好我问您一下，这周有计划那天发版吗？

**Comment by pissang** [comment]
@q604265262 不出意外的话这周五

**Comment by q604265262** [comment]
> @q604265262 不出意外的话这周五

好的 非常感谢

**Comment by realeve** [comment]
@pissang  谢谢了，15号能发版吧？目前项目中同时使用到了4.X跟5.0版，为了兼容水球图需要单独 导入一份 echarts4.min.js 。
![image](https://user-images.githubusercontent.com/448208/104602270-32211e80-56b6-11eb-903a-6ccbe6f783e3.png)

**Comment by pissang** [comment]
@realeve 预计今天晚上投票结束，明天发布 npm

**Comment by q604265262** [comment]
![QQ截图20210116151811](https://user-images.githubusercontent.com/32191557/104805881-37917c80-580e-11eb-88f7-19e85d0f1acc.png)

更新3.0后 报`external_echarts_.helper.enableHoverEmphasis is not a function` 错误 是实例水球有更改吗？

**Comment by pissang** [comment]
@q604265262 echarts 更新了吗？

**Comment by q604265262** [comment]
> @q604265262 echarts 更新了吗？

更新了 echarts 版本为5.0

**Comment by pissang** [comment]
@q604265262 奥，看了下这个应该是示例页 https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js 的缓存还没更新到最新，可以手动改成 https://cdn.jsdelivr.net/npm/echarts@5.0.1/dist/echarts.min.js

**Comment by q604265262** [comment]
> @q604265262 奥，看了下这个应该是示例页 https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js 的缓存还没更新到最新，可以手动改成 https://cdn.jsdelivr.net/npm/echarts@5.0.1/dist/echarts.min.js

可以了 非常感谢

**Comment by pissang** [comment]
Just published 3.0 to fix it

**Comment by zww930620** [comment]
项目npm升级了echarts(5.0.1), zrender(5.0.3),echarts-liquidfill(3.0.0), 水球图还是报错
![image](https://user-images.githubusercontent.com/33643702/105442211-bc641680-5ca4-11eb-8cfb-e817f5b57c3a.png)

**Comment by pissang** [comment]
@zww930620 可以在 codesandbox 上提供一个可以复现的例子么？

**Comment by peiyingzheng** [comment]
echarts5.0.2 n.helper.completeDimensions is not a function
![image](https://user-images.githubusercontent.com/79498566/108805078-10cb2080-75da-11eb-9927-08d81383d200.png)

**Comment by pissang** [comment]
echarts 版本是否是最新的

**Comment by peiyingzheng** [comment]
是最新的 echarts@5.0.2

**Comment by peiyingzheng** [comment]
是最新的 echarts@5.0.2

**Comment by peiyingzheng** [comment]
echarts是5.0.2版本，echart-gl是2.0.2版本，这两个版本兼容吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi Shen"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 中午1:50
收件人: "ecomfe/echarts-liquidfill"<echarts-liquidfill@noreply.github.com&gt;; 
抄送: "品月湛"<729884664@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ecomfe/echarts-liquidfill] with echarts@5.0.0, completeDimensions is not a function  (#120)





 
echarts 版本是否是最新的
