### ISSUE TITLE
with echarts@5.0.0:  parsePercent is not a function 

### ISSUE THREAD

**Issue by cheqianxiao** [ecomfe/echarts-liquidfill#121]
![image](https://user-images.githubusercontent.com/16025751/100694018-1cd38780-33c9-11eb-915a-1bacc24aee68.png)

`parsePercent` method is not exported anymore  
https://github.com/apache/incubator-echarts/blob/af811c6bcdb6ebca75d4d9688a85dac7ec365f35/src/export.ts#L55

plus: 
`echarts.graphic.setHoverStyle` is also not a function:      

![image](https://user-images.githubusercontent.com/16025751/100694525-3de8a800-33ca-11eb-9b29-afcfc25bf3b9.png)

**Comment by prashanthc97** [comment]
![image](https://user-images.githubusercontent.com/25387999/104499601-5b34a700-5603-11eb-8a49-ee6b6f7e089a.png)
Facing the same issue while integrating with liquidfill

**Comment by pissang** [comment]
Fixed in the latest version
