### ISSUE TITLE
使用 echarts@5

### ISSUE THREAD

**Issue by adamgogogo** [ecomfe/echarts-liquidfill#126]
使用 echarts@5

_Originally posted by @pissang in https://github.com/ecomfe/echarts-liquidfill/issues/124#issuecomment-770946532_

echarts4用哪个版本的liquidfill呢？

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts-liquidfill#install-echarts-liquidfill-with-npm

**Comment by adamgogogo** [comment]
谢谢
