### ISSUE TITLE
3.0 版本使用了 echarts 被弃用的 api

### ISSUE THREAD

**Issue by namecho** [ecomfe/echarts-liquidfill#129]
DEPRECATED: 'position' has been deprecated. use 'x', 'y' instead

**Comment by Ovilia** [comment]
3.0 版本需配合 ECharts 5.x 版本使用，建议升级到最新版 ECharts

**Comment by namecho** [comment]
就是使用了 Ehcart 5.0 被弃用的

**Comment by MafuyuRyan** [comment]
确实 希望能update一下

**Comment by pissang** [comment]
欢迎提 PR
