### ISSUE TITLE
请教怎么结合两种图表组件？

### ISSUE THREAD

**Issue by php-cpm** [ecomfe/echarts-liquidfill#13]
http://echarts.baidu.com/demo.html#graph

请问有没有办法把关系图的节点换成liquidfill呢？

**Comment by Ovilia** [comment]
不支持这样的功能。

以下是我的一些想法，你可以尝试一下。
先用 graph 添加这些数据，然后用 [echartsInstance.convertToPixel](http://echarts.baidu.com/api.html#echartsInstance.convertToPixel) 获得每个数据点的坐标。然后分别添加水球图，将 `center` 设为这些 pixel 的位置。

你试试看行不行~

**Comment by php-cpm** [comment]
http://gallery.echartsjs.com/editor.html?c=xryOZDG3gZ&v=2   似乎可行，细节还要再调整调整

**Comment by Ovilia** [comment]
赞！
