### ISSUE TITLE
请问水球图上部背景色如何不渐变，data值变化时背景色始终一致

### ISSUE THREAD

**Issue by BVDF2017** [ecomfe/echarts-liquidfill#130]
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
    }]
};
```
请问水球图上部背景色如何不渐变，data值变化时背景色始终一致？
目前测试发现data设置最小和最大值时，最上方的背景色会不一致。

![max1](https://user-images.githubusercontent.com/48642774/116051710-76f02480-a6ab-11eb-9676-7c68e365d448.png)

![min1](https://user-images.githubusercontent.com/48642774/116051823-94bd8980-a6ab-11eb-8415-eb9289143657.png)
同样背景色设为'red',但是还是有色差。

**Comment by Ovilia** [comment]
似乎是因为设置了阴影？

**Comment by BVDF2017** [comment]
> 似乎是因为设置了阴影？

目前还没有相应的修改设置方式吧

**Comment by Ovilia** [comment]
@BVDF2017 有啊，看文档啊 https://github.com/ecomfe/echarts-liquidfill#shadow
