### ISSUE TITLE
与 ECharts V5.1.1 使用无报错无效果

### ISSUE THREAD

**Issue by onsummer** [ecomfe/echarts-liquidfill#131]
已确认 ECharts 的 helloworld 示例代码能跑通，说明 ECharts 安装没问题。

![image](https://user-images.githubusercontent.com/26168955/117753881-daea1f80-b24b-11eb-8b86-75ffae057301.png)

![image](https://user-images.githubusercontent.com/26168955/117753686-7fb82d00-b24b-11eb-9fb3-9441b1758dd7.png)

![image](https://user-images.githubusercontent.com/26168955/117753725-8e9edf80-b24b-11eb-9141-a8c5d67d05de.png)

代码：

``` js
import React, { useEffect, useRef } from 'react'
import ReactDOM from 'react-dom'
import * as ECharts from 'echarts/core'
import {
  CanvasRenderer
} from 'echarts/renderers'

import './index.css'
ECharts.use([CanvasRenderer])

const App = (props) => {
  let chart;
  const chartRef = useRef()
  const option = {
    series: [{
      type: 'liquidFill',
      data: [0.6, 0.5, 0.4, 0.3]
    }]
  }

  useEffect(() => {
    chart = ECharts.init(chartRef.current)
    chart.setOption(option)
  }, [])


  return <div>
    <div style={{ width: "50vw", height: "50vh" }} ref={chartRef}></div>
  </div>
}

ReactDOM.render(
  <App></App>,
  document.getElementById('root')
)
```

环境：

``` json
{
  "dependencies": {
    "echarts": "^5.1.1",
    "echarts-liquidfill": "^3.0.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react-refresh": "^1.3.1",
    "vite": "^2.2.3"
  }
}
```

**Comment by Ovilia** [comment]
不要 `import * as ECharts from 'echarts/core'` 这样很可能少引用了什么组件，建议 `import * as echarts from 'echarts'` 先看看有没有问题

**Comment by onsummer** [comment]
在修改成您建议的代码后，报错改变了

``` jsx
import React, { useEffect, useRef } from 'react'
import ReactDOM from 'react-dom'
import * as echarts from 'echarts'
import {
  CanvasRenderer
} from 'echarts/renderers'

import './index.css'
echarts.use([CanvasRenderer])

const App = (props) => {
  let chart;
  const chartRef = useRef()
  const option = {
    series: [{
      type: 'liquidFill',
      data: [0.6, 0.5, 0.4, 0.3]
    }]
  }

  useEffect(() => {
    chart = echarts.init(chartRef.current)
    chart.setOption(option)
  }, [])


  return <div>
    <div style={{ width: "50vw", height: "50vh" }} ref={chartRef}></div>
  </div>
}

ReactDOM.render(
  <App></App>,
  document.getElementById('root')
)
```

![image](https://user-images.githubusercontent.com/26168955/117800547-d17da900-b285-11eb-84fd-d0a2de63f775.png)

虽然还是白白一片没有出来效果

**Comment by pissang** [comment]
@onsummer 没看到你有引用 liquid-fill 组件？

**Comment by ZhongHongLi** [comment]
5.0的肯定不信，你改4.9的版本，水波图的js也该改成2.0的版本试试

**Comment by onsummer** [comment]
> 5.0的肯定不信，你改4.9的版本，水波图的js也该改成2.0的版本试试

我换 ant chart 了...

**Comment by ZhongHongLi** [comment]
哦，也可以我看到有g2plot 有你用的是这个吗，他这个好坑新版的，方法少了一个，我也是搞了半天才好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ecomfe/echarts-liquidfill] 与 ECharts V5.1.1 使用无报错无效果 (#131)





  
5.0的肯定不信，你改4.9的版本，水波图的js也该改成2.0的版本试试
  
我换 ant chart 了...

**Comment by pissang** [comment]
跟老版本一样

```ts
import * from 'echarts';
import 'echarts-liquidfill'
```

就行了

**Comment by ZhongHongLi** [comment]
你这个还是高版本的吗，5.0的？我用的原生的js




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午3:55
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ecomfe/echarts-liquidfill] 与 ECharts V5.1.1 使用无报错无效果 (#131)





 
跟老版本一样
 import * as echarts from 'echarts'; import 'echarts-liquidfill'
 
就行了

**Comment by pissang** [comment]
echarts-liquidfill@3 对应 echarts@5
echarts-liquidfill@2 对应老版本的 echarts

**Comment by ZhongHongLi** [comment]
3的版本可以对应五没报错是吧，我去测试一下。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ecomfe/echarts-liquidfill] 与 ECharts V5.1.1 使用无报错无效果 (#131)





 
***@***.*** 对应 ***@***.***
 ***@***.*** 对应老版本的 echarts

**Comment by pissang** [comment]
@ZhongHongLi 嗯我写了一个简单的例子

https://codesandbox.io/s/brave-rosalind-dj280?file=/src/index.js

之前 README 上引入这部分有遗漏，我补充了一下

**Comment by onsummer** [comment]
感谢回复
