### ISSUE TITLE
Any idea for how to combine this tool with vue-echarts in a vue program?

### ISSUE THREAD

**Issue by DanielWLam** [ecomfe/echarts-liquidfill#14]
Any idea for how to combine this tool with vue-echarts in a vue program?

**Comment by DanielWLam** [comment]
[vue-echarts](https://github.com/Justineo/vue-echarts)

**Comment by Ovilia** [comment]
@Justineo Any idea?

**Comment by Justineo** [comment]
@DanielWLam It's the wrong place to ask. Let's continue this topic in [vue-echarts](https://github.com/Justineo/vue-echarts).

**Comment by DanielWLam** [comment]
I think I finally find out the real reason why browser would throw that error! The echarts module build in echart-liquidfill is old. Some modules like 'Model' still use define to declare a module. That is to say, the module `echarts-liquidfill` might should upgrade the dependencies...
