### ISSUE TITLE
设置背景为白色后，背景颜色会被波纹颜色给污染，怎么解决呢？

### ISSUE THREAD

**Issue by liulu663125** [ecomfe/echarts-liquidfill#148]
![image](https://user-images.githubusercontent.com/54014413/139367500-01a6be6c-f3d4-4027-92ff-b106a9727b3f.png)

背景色是白色，波纹色是蓝色
backgroundStyle: {
  color: "#fff"
},
color: ['#1A7AF7'],

**Comment by lsp113** [comment]
去掉水波上的阴影:
series：[
    itemStyle: {
               shadowBlur: 0
    },
]
