### ISSUE TITLE
echarts 3.6.1 console 存在错误信息

### ISSUE THREAD

**Issue by hustcc** [ecomfe/echarts-liquidfill#15]
## 代码

```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
    }]
};
```

## 错误信息

如下图所示：
![image](https://cloud.githubusercontent.com/assets/7856674/26661275/4d5d60b6-46af-11e7-81bd-5cb85c1e3513.png)

## 复现步骤

这个项目的 example 代码应该就可以看到错误。

或者

```js
git clone git@github.com:hustcc/echarts-for-react.git

cd echarts-for-react

npm i

npm run build

然后打开项目根目录 index.html，查看 Liquidfill 这个实例。

## 原因

大概是因为本项目依赖 echarts 的版本号是直接写的大于，所以 echarts 升级之后，导致自动安装最新的 3.6.1，然后兼容出错，我在本地 node_modules 中删除 3.6.1 版本，重新 build 就可以了。

**Comment by Ovilia** [comment]
这似乎是没引用 liquidfill 对应的 js？应该在 echarts.js 后引用 https://github.com/ecomfe/echarts-liquidfill/tree/master/dist

**Comment by hustcc** [comment]
在 react 中 require 的，大概找到原因了。

原因是 node_modules 中安装的 echarts 版本有3.5.x 和 3.6.1，然后就会出错，如果统一版本为 3.5 或者3.6 就不会出现这个问题。
