### ISSUE TITLE
webpack中引入echarts-liquidfill，运行报错

### ISSUE THREAD

**Issue by Sioxas** [ecomfe/echarts-liquidfill#16]
错误：Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-12) is negative.
![image](https://cloud.githubusercontent.com/assets/9740581/26726883/4db5744e-47d7-11e7-9ed1-4a25fe018ae4.png)

代码：
```js
import echarts from 'echarts'
import 'echarts-liquidfill'
let option = {
series: [{
            type: 'liquidFill',
            data: [0.20, 0.30, 0.15, 0.10],
            radius: '19%'
        }]
}
humidityDashboard = echarts.init(document.getElementById('humidity-dashboard'))
humidityDashboard.setOption(option)

```

**Comment by Ovilia** [comment]
换成别的 data 也一样报错吗？

**Comment by kingspp** [comment]
**Development Infrastructure:**

**Framework:** React
**Builder:** Webpack 2

**Temporary Solution:**
change radius >27
```javascript
import echarts from 'echarts'
import 'echarts-liquidfill'
let option = {
series: [{
            type: 'liquidFill',
            data: [0.20, 0.30, 0.15, 0.10],
            radius: 30
        }]
}
humidityDashboard = echarts.init(document.getElementById('humidity-dashboard'))
humidityDashboard.setOption(option)
```

**Comment by Ovilia** [comment]
@kingspp You should probably need a larger radius (try 300 perhaps). Open a new issue if you have further questions, rather than report unrelated problem in this issues. Thanks.
