### ISSUE TITLE
grid无效

### ISSUE THREAD

**Issue by dengshihao** [ecomfe/echarts-liquidfill#169]
<img width="640" alt="image" src="https://github.com/ecomfe/echarts-liquidfill/assets/33246402/ae38f68e-2ab7-4b41-a4f8-97ca72766311">

**Comment by dengshihao** [comment]
找到了，通过radius设置即可拉满画板

**Comment by junjie-lean** [comment]
> 找到了，通过radius设置即可拉满画板

你怎么设置的？能发下代码吗？
