### ISSUE TITLE
水球自定义（火狐浏览器出问题） 地址：http://gallery.echartsjs.com/editor.html?c=xH1HouM9Sl

### ISSUE THREAD

**Issue by Cassieqian** [ecomfe/echarts-liquidfill#17]
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
    }]
};
```

**Comment by Ovilia** [comment]
具体什么问题？我这边看是 ok 的，你把浏览器版本、操作系统，以及问题的表现说一下？

**Comment by Cassieqian** [comment]
canvas裁剪没有生效，波纹出去圆了。浏览器版本：火狐最新版本54.0  操作系统：win10

**Comment by Cassieqian** [comment]
var option = {
series: [{
type: 'liquidFill',
data: [0.6, 0.5, 0.4, 0.3],
backgroundStyle: {
    borderColor: '#156ACF',
    borderWidth: 2,
    color: '#E3F7FF',
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowBlur: 20
},

radius: '70%',
outline: {
    show: false
}
}]
};
如果在火狐中参数配置shadowBlur:20 会有问题，已经解决，谢谢
