### ISSUE TITLE
调用能显示但是报错

### ISSUE THREAD

**Issue by junjiem** [ecomfe/echarts-liquidfill#19]
var option = {
            tooltip: {
                formatter: "{a} <br/>{b} : {c}"
            },
            toolbox: {
                show : true,
                feature : {
                    mark : {show: false},
                    dataView : {show: true, readOnly: true},
                    //magicType : {show: true, type: ['line', 'bar']},
                    restore : {show: false},
                    saveAsImage : {show: true}
                }
            },
            series: [{
                type: 'liquidFill',
                shape: 'circle',
                data: [0.8, {
                    value: 0.75,
                    direction: 'left'
                }],
                radius: '70%',
                outline: {
                    show: false
                },
                backgroundStyle: {
                    borderWidth: 2,
                    borderColor: '#156ACF'
                },
                amplitude: 10,
                waveAnimation: true,
                silent: false
            }]
        };

**Comment by junjiem** [comment]
![1500898991 1](https://user-images.githubusercontent.com/6293598/28523225-fcce49a2-70ad-11e7-84f7-6b5bee892c55.png)

**Comment by Ovilia** [comment]
升级到最新版本了吗？

**Comment by junjiem** [comment]
最新的

**Comment by junjiem** [comment]
echarts版本吗？

**Comment by Ovilia** [comment]
ECharts 以及水球图的。这个错误以前是发生过，后来修复了，升级到最新版的应该就可以。
