### ISSUE TITLE
萌新 落落的问 个问题

### ISSUE THREAD

**Issue by z253573760** [ecomfe/echarts-liquidfill#21]
在vue中怎么引入 这个气泡球插件

Error: Component series.liquidFill not exists. Load it first.
堆栈跟踪：
clazz.enableClassManagement/entity.getClass@webpack-internal:///23:166:23
visitComponent/<@webpack-internal:///440:195:51
each@webpack-internal:///0:263:13
visitComponent@webpack-internal:///440:178:17
componentUtil.enableTopologicalTravel/entity.topologicalTravel@webpack-internal:///89:89:21
mergeOption@webpack-internal:///440:147:13
initBase@webpack-internal:///440:642:9
resetOption@webpack-internal:///440:92:21
setOption@webpack-internal:///440:74:13
echartsProto.setOption@webpack-internal:///1:279:9
initChart@webpack-internal:///208:65:7
boundFn@webpack-internal:///17:184:9
mounted@webpack-internal:///208:27:5
callHook@webpack-internal:///17:2666:9
insert@webpack-internal:///17:3527:7
invokeInsertHook@webpack-internal:///17:5470:9
patch@webpack-internal:///17:5640:5
lifecycleMixin/Vue.prototype._update@webpack-internal:///17:2425:16
updateComponent@webpack-internal:///17:2539:7
get@webpack-internal:///17:2882:13
run@webpack-internal:///17:2959:17
flushSchedulerQueue@webpack-internal:///17:2725:5
queueNextTick/<@webpack-internal:///17:702:11
nextTickHandler@webpack-internal:///17:649:7

**Comment by sunshineYe** [comment]
在echarts/index.js里面加上require('../echarts-liquidfill/index')就可以了，试试看~
