### ISSUE TITLE
require 报错？

### ISSUE THREAD

**Issue by pylSER** [ecomfe/echarts-liquidfill#22]
报错如下:
Uncaught Error: Mismatched anonymous define() module: function (__WEBPACK_EXTERNAL_MODULE_2__) ....

感觉这个 js 的插件化不够啊

**Comment by Ovilia** [comment]
你是怎么用的？什么信息都不给怎么帮你解决问题？

**Comment by pylSER** [comment]
之前又引了另一个库，情况比较复杂，算了。谢谢！
