### ISSUE TITLE
vue webpack 报  in mounted hook: "Error: Component series.liquidFill not exists. Load it first."

### ISSUE THREAD

**Issue by liangwenle** [ecomfe/echarts-liquidfill#24]
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
    }]
};
```

**Comment by Ovilia** [comment]
要加载 liquidfill.js

**Comment by yjb1995** [comment]
![image](https://user-images.githubusercontent.com/20196885/30118075-a6ee5832-9354-11e7-9e1d-ec8a4b8157ff.png)

**Comment by yjb1995** [comment]
npm install 之后，不知道如何使用？

**Comment by Ovilia** [comment]
怎么加载 echarts 的就怎么加载，要在 echarts 之后加载。你可以把加载的代码放上来我看看。

**Comment by SynChron1zed** [comment]
@yjb1995  @Ovilia  2位 我也遇到同样问题 
![image](https://user-images.githubusercontent.com/18717051/30265855-0e4f8a50-9710-11e7-95fe-0bcd3deceab8.png)

![image](https://user-images.githubusercontent.com/18717051/30265872-1d303aec-9710-11e7-88ab-c48b054a6e58.png)

代码这样的 应该怎么改

**Comment by Ovilia** [comment]
`import echartsli from 'echarts-liquidfill'` 改为 `import 'echarts-liquidfill'`；
series 的 type 是字符串 `'echarts-liquidfill'`。
@SynChron1zed

**Comment by SynChron1zed** [comment]
@Ovilia 
![image](https://user-images.githubusercontent.com/18717051/30268307-eb000ee6-9717-11e7-9811-b78f77b76d9f.png)

![image](https://user-images.githubusercontent.com/18717051/30268388-187b6ce4-9718-11e7-91ee-f1963a169fb4.png)

![image](https://user-images.githubusercontent.com/18717051/30268400-223e8176-9718-11e7-8cd1-e5a048f0ee4f.png)
还是报错

**Comment by SynChron1zed** [comment]
@Ovilia  哥们 能抽时间帮看下不 很急哇 是版本问题么

**Comment by yjb1995** [comment]
有可能是版本问题

**Comment by yjb1995** [comment]
![image](https://user-images.githubusercontent.com/20196885/30271779-14cf5aea-9724-11e7-9075-34cb125b5d63.png)
![image](https://user-images.githubusercontent.com/20196885/30271785-1e126962-9724-11e7-932c-f6c85d83f267.png)
option没什么好说的echarts是3.7.1         liquidfill是1.1.1 都是用npm安装的

**Comment by yjb1995** [comment]
@SynChron1zed

**Comment by SynChron1zed** [comment]
@yjb1995 
但是我版本都是最新的
![image](https://user-images.githubusercontent.com/18717051/30273448-991ff7ee-972b-11e7-830e-c676dc3e393e.png)
而且现在我把echarts升到3.7.1后 
![image](https://user-images.githubusercontent.com/18717051/30273472-af79c77c-972b-11e7-9ff9-d3d6aac435f6.png)
现在报这个错了

**Comment by yjb1995** [comment]
@SynChron1zed你把引入方式改成和我一样试一下 
![image](https://user-images.githubusercontent.com/20196885/30273646-7de5c84a-972c-11e7-939c-603721fd38bb.png)

**Comment by SynChron1zed** [comment]
@yjb1995  没用 而且报这个错 
![image](https://user-images.githubusercontent.com/18717051/30274046-535eb42c-972e-11e7-92c3-adf4cd928f8d.png)

![image](https://user-images.githubusercontent.com/18717051/30274065-6370c3d2-972e-11e7-8ca7-984ab6d03994.png)

**Comment by SynChron1zed** [comment]
@yjb1995  我把echarts-liquidfill 删了 重新npm后 按照你的require 还是报之前的错

**Comment by yjb1995** [comment]
还有一种方式，在html中 用导入js文件的方法，吧echarts和liquidfill的js文件导进去，然后直接可以用了

**Comment by yjb1995** [comment]
@SynChron1zed

**Comment by SynChron1zed** [comment]
@yjb1995 

试了 一开始就从index.html 倒进去的 还是报错

**Comment by yjb1995** [comment]
@SynChron1zed 额。。这我上次报错是 因为我用的是echarts-for-react，所以没有echarts ，才报错，把echarts导进去后就好了

**Comment by SynChron1zed** [comment]
@yjb1995 头大啊  我也不知道问题出在哪里了 npm 里面的example 可以看出来

**Comment by yjb1995** [comment]
@SynChron1zed 所以配置这种东西最好复制不要手敲

**Comment by SynChron1zed** [comment]
@yjb1995  是的 谢谢咯  但是我觉得这个大小写 应该忽略的

**Comment by confidence68** [comment]
遇到相同问题，用npm or cnpm install echarts-liquidfill 就会出现Component series.liquidFill not exists. Load it first.

然后把node_modules删掉，用yarn重新安装了一下，就好了！

请问这是为什么？cnpm 也是提示安装成功了，node_modules也能找到，也引入了，但是就是提示找不到！
