### ISSUE TITLE
水位图在svg模式下出现波浪溢出的情况

### ISSUE THREAD

**Issue by jackfxq** [ecomfe/echarts-liquidfill#30]
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
    }]
};
```

水位图在svg模式下如果echarts租价过多的话出现波浪溢出的情况，现在水位图支持svg模式吗？
echarts:3.8.3;
浏览器：chrome62

**Comment by Ovilia** [comment]
目前还没有很好支持 SVG，后面会改进的

**Comment by Ovilia** [comment]
@jackfxq 请问“如果echarts租价过多的话”是什么意思？

**Comment by jackfxq** [comment]
就是把折线图、柱状图、水位图放在一起的时候有，单的的水位图时没有的，这个大概啥时候支持svg呢？

**Comment by Ovilia** [comment]
争取元旦前支持吧~

**Comment by jackfxq** [comment]
好的 谢谢

**Comment by Ovilia** [comment]
试一下 ECharts 4.0.2 版本和本项目的 2.0.0 版本，这个问题应该修复了。

**Comment by AltmanIss** [comment]
水位图可以加本地的图片吗
