### ISSUE TITLE
label 无法隐藏

### ISSUE THREAD

**Issue by MwumLi** [ecomfe/echarts-liquidfill#34]
代码如下, 并不能隐藏 label
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]，
        label: {
           normal: {
               show: false
            }
         }
    }]
};
```

在线访问这里: http://gallery.echartsjs.com/editor.html?c=xBJK1sFagG&v=2

看到 API 上写着设置 label.normal.show 决定 label 的显示或不显示, 但实际没生效, 不知是我理解错了？

**Comment by hanfengcan** [comment]
我也有这个问题,然后在format里面设置

**Comment by Ovilia** [comment]
请更新到 ECharts 4.0.2 和本项目的 2.0.0 版本，应该已经解决了。

**Comment by wangmingquan** [comment]
"echarts": "^4.3.0",
"echarts-liquidfill": "^2.0.5",


问题依然在，show，font-siz、opacity、color 全部不生效，根本隐藏不掉

**Comment by Ovilia** [comment]
请问具体的版本是多少？建议写死版本号，因为 `^` 可能包括 `2.0.4` 等版本。

**Comment by wangmingquan** [comment]
> 请问具体的版本是多少？建议写死版本号，因为 `^` 可能包括 `2.0.4` 等版本。

好了，非常感谢。但是官方的示例那还不行，建议也升级一下版本。
