### ISSUE TITLE
vue中如何引入水球这个插件。貌似echarts读取不到水球这个类型

### ISSUE THREAD

**Issue by zxxwslq** [ecomfe/echarts-liquidfill#35]
会报这个错误，**Component series.liquidFill not exists. Load it first.**。
引用方式是这样的：
import echarts from 'echarts'
import liquidfill from 'echarts-liquidfill'

**Comment by Ovilia** [comment]
import echarts from 'echarts'
import 'echarts-liquidfill'
试试？

**Comment by lin-Agoni** [comment]
之前我是这样引用的
import echarts from 'echarts'
import liquidfill from 'echarts-liquidfill'
console.log(liquidfill) 显示为空
改成
import echarts from 'echarts'
import 'echarts-liquidfill'
也没有用啊  求助

**Comment by Ovilia** [comment]
`console.log(liquidfill)` 没有这样使用的方式的，只要 `console.log(echarts)` 是对的，然后 setOption 的时候设置 series type 是 `'liquidFill'` 就行，注意大小写。 @lin-Agoni

**Comment by Lenhart1992** [comment]
import echarts from 'echarts'
import "echarts-liquidfill/src/liquidFill.js";
这样是可以的

**Comment by shuzihao** [comment]
我怎么每种方法都报错
