### ISSUE TITLE
如何关闭点击事件？

### ISSUE THREAD

**Issue by FatDong1** [ecomfe/echarts-liquidfill#38]
hello，现在在项目可以很好的展示，但是点击的时候水球内填充的颜色会改变，请问博主如何禁止掉？

**Comment by FatDong1** [comment]
谢谢

**Comment by Ovilia** [comment]
完全禁用的话：silient: true；
如果只是不想改颜色的话，可以把 emphasis 的颜色和其他属性设为和 normal 一样的

**Comment by FatDong1** [comment]
非常感谢！
