### ISSUE TITLE
【IOS8】Uncaught Error: IndexSizeError: DOM Exception 1

### ISSUE THREAD

**Issue by FatDong1** [ecomfe/echarts-liquidfill#39]
在IOS8会报错Uncaught Error: IndexSizeError: DOM Exception 1

**Comment by FatDong1** [comment]
https://stackoverflow.com/questions/15328764/html2canvas-error-uncaught-error-indexsizeerror-dom-exception-1/21047782#21047782

**Comment by FatDong1** [comment]
http://chronicles.blog.ryanrampersad.com/2010/06/index_size_err-dom-exception-1-html-canvas/

**Comment by FatDong1** [comment]
https://stackoverflow.com/questions/2444073/canvas-javascript-uncaught-error-index-size-err-dom-exception-1

**Comment by Ovilia** [comment]
复现条件是什么？canvas 有没有长宽？基本的 ECharts 折线图之类有没有这个问题？

**Comment by FatDong1** [comment]
`const companyContractTotal = {
  series: [{
    type: 'liquidFill',
    radius: '95%',
    data: [{
      name: '完成率',
      value: 0.75,
      direction: 'right',
      itemStyle: {
        normal: {
          color: '#d2f4a8',
          shadowBlur: 0
        },
        emphasis: {
          color: '#d2f4a8',
          shadowBlur: 0
        }
      }
    }, {
      value: 0.65,
      direction: 'right',
      itemStyle: {
        normal: {
          color: '#b2e87d',
          shadowBlur: 0
        },
        emphasis: {
          color: '#b2e87d',
          shadowBlur: 0
        }
      }
    }],
    outline: {
      borderDistance: 2,
      itemStyle: {
        borderWidth: 4,
        borderColor: '#F1F1F2',
        shadowBlur: 0
      }
    },
    backgroundStyle: {
      color: '#fff'
    },
    label: {
      normal: {
        insideColor: '#484759',
        color: '#484759',
        fontSize: 22,
        align: 'center',
        baseline: 'left'
      }
    }
  }]
}

export default companyContractTotal
`
从后台服务器获取数据之后，setOption之前包裹canvas的`div`是有宽高的
只是在ios8才会出现这个问题，安卓和其他机型不会

**Comment by Ovilia** [comment]
@pissang 帮忙测一下 ios8？

**Comment by halilibrahim** [comment]
Usage of liquidFill in our project:
```javascript
for (const b in window.baraj) {
  var chart = echarts.init(document.getElementById(b));
  var val = baraj[b].value / 100,
    bData = [{
      name: baraj[b].title,
      value: val
    }];
  for (var j = 0; j < 3; j++) {
    bData.push(val = val - 0.1);
  }
  chart.setOption({
    series: [{
      type: 'liquidFill',
      data: bData,
      radius: '90%',
      label: {
        formatter: function (param) {
          return param.name + '\n' + (param.value * 100) + '%';
        },
        fontSize: cnt.height() < 110 ? 14 : 18
      },
      outline: {
        show: true,
        borderDistance: 5,
        itemStyle: {
          borderWidth: 5,
          borderColor: '#40beed'
        }
      },
    }]
  });
  gaugeCharts.push(chart);
  i++;
}
```

Here is the stacktrace of the error: http://sentry.kaitek.com.tr/share/issue/d2c7c2f882044ee682701c67b8d7351c/

**Comment by Ovilia** [comment]
Fixed in https://github.com/ecomfe/echarts-liquidfill/commit/e6b85d99bd3e396fd0f630fe33958a9c36f9c8b3
