### ISSUE TITLE
click事件怎么写?

### ISSUE THREAD

**Issue by duzh** [ecomfe/echarts-liquidfill#4]
单击 或者其他事件怎么写. 使用官方的on方法绑定的事件对这个无效.如果能单独实现也可以, 能否给个示例?

**Comment by Ovilia** [comment]
设置方法和其他图表一样用 `on`：
```js
chart.on('click', function (params) {
    // 控制台打印数据的名称
    console.log(params);
});
```
也和其他图表一样，只有点击数据项（比如柱状图的柱子、折线图的折点）才会触发这一事件。在水球图中，只有点击水波才会触发这一事件。

如果想要实现点击任意位置的事件，可以通过图表监听 zrender 事件：
```js
chart.getZr().on('click', function() {
       console.log(arguments);
});
```
