### ISSUE TITLE
用 webpack import 或者 require 模式引入 import LiquidFill from 'echarts-liquidfill' 时报错

### ISSUE THREAD

**Issue by erickwang** [ecomfe/echarts-liquidfill#41]
同样是插件 import Wordcloud from 'echarts-wordcloud'; 引入是没有问题的。
但是 import LiquidFill from 'echarts-liquidfill' 后面报错了。
是不是插件写得有问题？

![错误](http://chuantu.biz/t6/208/1516179394x-1404793011.png)

```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
    }]
};
```

**Comment by erickwang** [comment]
echarts 4.0.1 可以加载成功，以上的错误是 3.8.5 会出现

**Comment by Ovilia** [comment]
`import 'echarts-liquidfill';` 即可，反正 `LiquidFill` 也是用不到的
