### ISSUE TITLE
为什么angular引入会报错

### ISSUE THREAD

**Issue by QiZZ121** [ecomfe/echarts-liquidfill#45]
![image](https://user-images.githubusercontent.com/26375138/35804047-0b1e3150-0ab1-11e8-8db3-ab424c2783e1.png)
![image](https://user-images.githubusercontent.com/26375138/35804074-2953e426-0ab1-11e8-872a-7c0b9c3e01dd.png)

**Comment by QiZZ121** [comment]
不知道怎么解决，求教

**Comment by Ovilia** [comment]
引用方式似乎没错，npm install 了吗？

**Comment by QiZZ121** [comment]
@Ovilia 这种方式引入没有用报这个错误，后来改直接在页面或者angular-cli文件加载这两个js文件才正常了

**Comment by QiZZ121** [comment]
@Ovilia  cnpm安装正常啊

**Comment by Ovilia** [comment]
那现在解决了吗？
