### ISSUE TITLE
在Echarts4.0+以上会报错，不能执行渲染

### ISSUE THREAD

**Issue by oo2o** [ecomfe/echarts-liquidfill#47]
在Echarts4.0+以上会报错，不能执行渲染

**Comment by liumiaoxiang** [comment]
在Echarts4.0+以上会报错，不能执行渲染

**Comment by OakWang** [comment]
有解决办法吗？一直刷这个错：
echarts-liquidfill.min.js:1 Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-12) is negative.

**Comment by OverNothing** [comment]
Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-12) is negative.
我在使用下面链接里的例子时遇到了这个问题，有什么解决方案吗？
http://gallery.echartsjs.com/editor.html?c=xH1-HeJj2G&v=2

**Comment by Ovilia** [comment]
请使用最新发布的 2.0.1 版本，与 ECharts 4.1.0 版本兼容。

**Comment by clark1201** [comment]
package.json
`
"echarts": "^4.1.0",
"echarts-liquidfill": "^2.0.1",
`

index.js

import echartsliquidfill from'echarts-liquidfill/dist/echarts'
import 'echarts-liquidfill/dist/echarts-liquidfill'
const p1 = $(`.lf`)[0]
var option = {
        series: [{
          type: 'liquidFill',
          data: [0.6]
        }]
      };
const lf = echartsliquidfill.init(p1)
lf.setOption(option)


> Component series.liquidFill not exists. Load it first.
