### ISSUE TITLE
disponse 警告

### ISSUE THREAD

**Issue by jiangshangzheng** [ecomfe/echarts-liquidfill#5]
调用disponse 方法时报如下警告，望解决，谢谢
Method `dispose` should be implemented in liquidFill.

**Comment by Mignon-han** [comment]
在echart源文件中，把 `‘liquidFill’` 添加到 `COMPATITABLE_SERIES`数组中就可以了
![liquidfill](https://cloud.githubusercontent.com/assets/16368087/25127031/ef9a3c02-2466-11e7-9969-22524f438bfa.png)
