### ISSUE TITLE
npm 引入的 2.0.0 版本对应哪一个版本的 echarts

### ISSUE THREAD

**Issue by ubuntugx** [ecomfe/echarts-liquidfill#53]
请问 npm 引入的 2.0.0 版本对应哪一个版本的 echarts？使用了 3.8.0 和 4.0.0 分别报了 `Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-12) is negative. ` 和 `Component series.liquidFill not exists.` 的错误

**Comment by Ovilia** [comment]
4.0.2

**Comment by DongJunSir** [comment]
node里面使用echarts和echarts-liquidfillsss
 "echarts": "4.0.2",
    "echarts-liquidfill": "^2.0.0",
报错 <this._rawData.getSource is not a function>
谁遇到过？怎么解决？？

**Comment by Ovilia** [comment]
请使用最新发布的 2.0.1 版本，与 ECharts 4.1.0 版本兼容。
