### ISSUE TITLE
Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-12) is negative.

### ISSUE THREAD

**Issue by kimoyoyo21** [ecomfe/echarts-liquidfill#56]
Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-12) is negative.

 var echartDom = document.getElementById('echart2-liquidFill');
            var myChart = echarts.init(echartDom);
            var option = {
                series: [{
                type: 'liquidFill',
                data: [0.6, 0.5, 0.4, 0.3]
                }]
            };
            myChart.setOption(option);

**Comment by Ovilia** [comment]
4.0.2 版本还有这个问题吗？

**Comment by clark1201** [comment]
4.0.2有这个版本吗？

**Comment by clark1201** [comment]
把 echarts 版本控制在4.0.0 ,echarts-liquidfill版本 2.0.1
然后在容器上指定高宽就 ok 了。

**Comment by Ovilia** [comment]
@guoyan997 亲测 echarts: 4.1.0, echarts-liquidfill: 2.0.1 没问题，是容器没有宽度高度吗？
