### ISSUE TITLE
shape配置项

### ISSUE THREAD

**Issue by xuexiaoao** [ecomfe/echarts-liquidfill#61]
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
shape: 'path://M367.855,428.202c-3.674-1.385-7.452-1.966-11.146-1.794c0.659-2.922,0.844-5.85,0.58-8.719 c-0.937-10.407-7.663-19.864-18.063-23.834c-10.697-4.043-22.298-1.168-29.902,6.403c3.015,0.026,6.074,0.594,9.035,1.728 c13.626,5.151,20.465,20.379,15.32,34.004c-1.905,5.02-5.177,9.115-9.22,12.05c-6.951,4.992-16.19,6.536-24.777,3.271 c-13.625-5.137-20.471-20.371-15.32-34.004c0.673-1.768,1.523-3.423,2.526-4.992h-0.014c0,0,0,0,0,0.014 c4.386-6.853,8.145-14.279,11.146-22.187c23.294-61.505-7.689-130.278-69.215-153.579c-61.532-23.293-130.279,7.69-153.579,69.202 c-6.371,16.785-8.679,34.097-7.426,50.901c0.026,0.554,0.079,1.121,0.132,1.688c4.973,57.107,41.767,109.148,98.945,130.793 c58.162,22.008,121.303,6.529,162.839-34.465c7.103-6.893,17.826-9.444,27.679-5.719c11.858,4.491,18.565,16.6,16.719,28.643 c4.438-3.126,8.033-7.564,10.117-13.045C389.751,449.992,382.411,433.709,367.855,428.202z'
    }]
};
```

path://后面的路径怎么获得呐，是否还支持其他的图片引入方式呢

**Comment by xuexiaoao** [comment]
已经找到这个路径的获取方式了

**Comment by LIHAO520** [comment]
shape: 'path://../../../../assets/img/floatImg2.png',为什么我这样写图片没有进来，那个波纹动画也没有了

**Comment by xuexiaoao** [comment]
> shape: 'path://../../../../assets/img/floatImg2.png',为什么我这样写图片没有进来，那个波纹动画也没有了

图片时svg格式，直接引入png是不行的

**Comment by LIHAO520** [comment]
怎么转svg格式是要ui提供吗还是啥

**Comment by LIHAO520** [comment]
path://../../../../assets/img/gen.svg这种格式也不对，  我用http://www.bejson.com/convert/image_to_svg/这个网站在线转换然后下载下来的， 并且它生成的格式不是M这种开头的href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXAAAAFwCAYAAAChGSA/AAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAA是这样的，请问，我是哪个环境出错了嘛

**Comment by xuexiaoao** [comment]
> path://../../../../assets/img/gen.svg这种格式也不对， 我用[http://www.bejson.com/convert/image_to_svg/这个网站在线转换然后下载下来的，](http://www.bejson.com/convert/image_to_svg/%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E5%9C%A8%E7%BA%BF%E8%BD%AC%E6%8D%A2%E7%84%B6%E5%90%8E%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E7%9A%84%EF%BC%8C) 并且它生成的格式不是M这种开头的href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXAAAAFwCAYAAAChGSA/AAAABGdBTUEAALGPC/xhBQAAACBjSFJN
> AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAA是这样的，请问，我是哪个环境出错了嘛

你转换的格式好像是base64的呀，并不是svg吧，你可以让你们的ui提供一份svg格式的就可以呀

**Comment by LIHAO520** [comment]
好的。多谢老铁

**Comment by LIHAO520** [comment]
老铁，它给我就是一张svg格式的图片。还是没有生效啊shape: 'path://../../../assets/img/sixImg.svg',
我还要做什么转换吗

**Comment by xuexiaoao** [comment]
> 老铁，它给我就是一张svg格式的图片。还是没有生效啊shape: 'path://../../../assets/img/sixImg.svg',
> 我还要做什么转换吗

你用记事本之类的文本编辑器打开svg图片，就会找到类似下面path后面的字符串了，然后直接替换上就可以了。我不是前端，可能描述的不太准确。。。。
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
shape: 'path://M367.855,428.202c-3.674-1.385-7.452-1.966-11.146-1.794c0.659-2.922,0.844-5.85,0.58-8.719 c-0.937-10.407-7.663-19.864-18.063-23.834c-10.697-4.043-22.298-1.168-29.902,6.403c3.015,0.026,6.074,0.594,9.035,1.728 c13.626,5.151,20.465,20.379,15.32,34.004c-1.905,5.02-5.177,9.115-9.22,12.05c-6.951,4.992-16.19,6.536-24.777,3.271 c-13.625-5.137-20.471-20.371-15.32-34.004c0.673-1.768,1.523-3.423,2.526-4.992h-0.014c0,0,0,0,0,0.014 c4.386-6.853,8.145-14.279,11.146-22.187c23.294-61.505-7.689-130.278-69.215-153.579c-61.532-23.293-130.279,7.69-153.579,69.202 c-6.371,16.785-8.679,34.097-7.426,50.901c0.026,0.554,0.079,1.121,0.132,1.688c4.973,57.107,41.767,109.148,98.945,130.793 c58.162,22.008,121.303,6.529,162.839-34.465c7.103-6.893,17.826-9.444,27.679-5.719c11.858,4.491,18.565,16.6,16.719,28.643 c4.438-3.126,8.033-7.564,10.117-13.045C389.751,449.992,382.411,433.709,367.855,428.202z'
    }]
};
```

**Comment by LIHAO520** [comment]
<svg id="图层_1" data-name="图层 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132.5 152"><title>六边形</title><polygon points="65.75 0 132.5 38 132.5 114 66.25 152 0 114 0 38 65.75 0"/></svg>我打开之后是这样的，全部复制过去也没有生效，用后面那段也没有生效。老铁。你用记事本生成之后是这样的吗

**Comment by LIHAO520** [comment]
老铁，'path://后面的那个M开头那段字符串，我的没有；我的是<polygon points="65.75 0 132.5 38 132.5 114 66.25 152 0 114 0 38 65.75 0"/>  然后是一个svg的标签包着的，老铁你打开是啥样的。帮帮忙

**Comment by xuexiaoao** [comment]
> 老铁，'path://后面的那个M开头那段字符串，我的没有；我的是 然后是一个svg的标签包着的，老铁你打开是啥样的。帮帮忙
我的打开是这个样子的
![image](https://user-images.githubusercontent.com/18185523/56484394-f584bb00-6501-11e9-81af-0d5076486dab.png)

**Comment by LIHAO520** [comment]
![image](https://user-images.githubusercontent.com/35720047/56484502-65934100-6502-11e9-8963-16774f4c44d1.png)
我打开是这样的，都没有这个path的一些路径，你是直接把path后面那段复制过去就可以了是吗？我没有这咋搞，我全部复制过去也没有用。只复制polygon这个标签里的也没有生效，这是什么情况

**Comment by xuexiaoao** [comment]
> ![image](https://user-images.githubusercontent.com/35720047/56484502-65934100-6502-11e9-8963-16774f4c44d1.png)
> 我打开是这样的，都没有这个path的一些路径，你是直接把path后面那段复制过去就可以了是吗？我没有这咋搞，我全部复制过去也没有用。只复制polygon这个标签里的也没有生效，这是什么情况

这个我就不清楚了。你可以先找别的svg试试，如果引用path后面那段没问题，是不是可以找找你们的UI问问你的svg为什么没有path呢。。。
