### ISSUE TITLE
指定渲染器为 svg 时，报错

### ISSUE THREAD

**Issue by Priccc** [ecomfe/echarts-liquidfill#62]
![image](https://user-images.githubusercontent.com/17777028/44145042-9b9cab52-a0bc-11e8-8a5f-9d36423510dc.png)

**Comment by Ovilia** [comment]
ECharts 和 水球图的版本？代码？

**Comment by Priccc** [comment]
@Ovilia 
我是在 react-native 上使用的，贴上部分代码，
文件都是从master分支上下载的最新代码
而且 echarts.js 只能引用完整代码，使用精简代码不出图
```
const chart = echarts.init(document.getElementById('main'), null, { renderer: 'svg' });

series: [{
     type: 'liquidFill',
     data: [0.6]
 }]
```

**Comment by Ovilia** [comment]
你试试使用不压缩的 ECharts，然后看看报错的地方定位在哪里

**Comment by Priccc** [comment]
@Ovilia 
改用未压缩版本
![image](https://user-images.githubusercontent.com/17777028/44185044-9ede0a80-a144-11e8-900f-739080a55b75.png)
```
定位在了 `var aa = a[0];`
/**
 * 旋转变换
 * @param {Float32Array|Array.<number>} out
 * @param {Float32Array|Array.<number>} a
 * @param {number} rad
 */
function rotate(out, a, rad) {
    var aa = a[0];
    var ac = a[2];
    var atx = a[4];
    var ab = a[1];
    var ad = a[3];
    var aty = a[5];
    var st = Math.sin(rad);
    var ct = Math.cos(rad);

    out[0] = aa * ct + ab * st;
    out[1] = -aa * st + ab * ct;
    out[2] = ac * ct + ad * st;
    out[3] = -ac * st + ct * ad;
    out[4] = ct * atx + st * aty;
    out[5] = ct * aty - st * atx;
    return out;
}
```

**Comment by Ovilia** [comment]
这个问题在 https://github.com/ecomfe/zrender/commit/0cc622196d8665f40d02b6156450cc7a87fe3a67 修复了，是在 4.1.0 之后的，目前还没发版，急着用的话可以自己编译（http://www.echartsjs.com/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9E%84%E5%BB%BA%20ECharts）或者先用 Canvas 版，预计本月内发不了新版。
