### ISSUE TITLE
为什么 default text is 60%

### ISSUE THREAD

**Issue by fhqdgv** [ecomfe/echarts-liquidfill#7]
> By default, the text label of liquid fill chart displays percentage of the first data. For example, for a chart with data [0.6, 0.5, 0.4, 0.3], default text is 60%.
为什么只显示一个数据，应该象饼图那样，可以在很个数据区域显示文字。
而且还有一个bug，label.normal.show: false时文字依然显示
http://gallery.echartsjs.com/editor.html?c=xryw_AqPhl&v=2

**Comment by Ovilia** [comment]
因为水球图主要是用来显示一个数据的，其他数据是用来辅助波浪样式的，如果需要，可以自定义文字内容
