### ISSUE TITLE
vue cli 3.0 - echarts 4.1.0 - liquidfill 2.0.2 -> Error: Component series.liquidFill not exists. Load it first.

### ISSUE THREAD

**Issue by leonnnop** [ecomfe/echarts-liquidfill#70]
```
created() {
            this.$nextTick(() => {
                var echarts = require('echarts');
                require('echarts-liquidfill')
                
                // 基于准备好的dom，初始化echarts实例
                var myChart = echarts.init(document.getElementById('waterFill'));

                // 指定图表的配置项和数据
                var option = {
                    series: [{
                        type: 'liquidFill',
                        data: [0.6, 0.5, 0.4, 0.3],
                        outline: {
                            show: false
                        }
                    }]
                };
           
                myChart.setOption(option);
            })
        }
```

```
  "dependencies": {
    "echarts": "^4.1.0-rc.2",
    "echarts-liquidfill": "^2.0.2",
```
尝试了各种issue里提到过的解决办法，都无法解决 Error: Component series.liquidFill not exists. Load it first. 跪倒，求助。

**Comment by Ovilia** [comment]
试下 ECharts 4.1.0？不要 rc 的

**Comment by NPZ000** [comment]
> 试下 ECharts 4.1.0？不要 rc 的

4.1.0 也不行啊  大佬

**Comment by NPZ000** [comment]
> ```
> created() {
>             this.$nextTick(() => {
>                 var echarts = require('echarts');
>                 require('echarts-liquidfill')
>                 
>                 // 基于准备好的dom，初始化echarts实例
>                 var myChart = echarts.init(document.getElementById('waterFill'));
> 
>                 // 指定图表的配置项和数据
>                 var option = {
>                     series: [{
>                         type: 'liquidFill',
>                         data: [0.6, 0.5, 0.4, 0.3],
>                         outline: {
>                             show: false
>                         }
>                     }]
>                 };
>            
>                 myChart.setOption(option);
>             })
>         }
> ```
> ```
>   "dependencies": {
>     "echarts": "^4.1.0-rc.2",
>     "echarts-liquidfill": "^2.0.2",
> ```
> 尝试了各种issue里提到过的解决办法，都无法解决 Error: Component series.liquidFill not exists. Load it first. 跪倒，求助。

你的问题解决了吗

**Comment by NPZ000** [comment]
"echarts": "^3.8.5",
    "echarts-liquidfill": "^1.0.5",

**Comment by NPZ000** [comment]
这个可以

**Comment by NPZ000** [comment]
1.0.5的版本setOption刷新数据的时候 报栈溢出的错误  怎么解决啊

**Comment by NPZ000** [comment]
RangeError: Maximum call stack size exceeded

**Comment by leonnnop** [comment]
> 试下 ECharts 4.1.0？不要 rc 的

抱歉回复的这么晚！但是4.1.0也无法解决问题，使用了另一位朋友提供的：
"echarts": "^3.8.5",
"echarts-liquidfill": "^1.0.5",
解决了出现了问题。

**Comment by Ovilia** [comment]
> > 试下 ECharts 4.1.0？不要 rc 的
> 
> 抱歉回复的这么晚！但是4.1.0也无法解决问题，使用了另一位朋友提供的：
> "echarts": "^3.8.5",
> "echarts-liquidfill": "^1.0.5",
> 解决了出现了问题。

请使用 "echarts-liquidfill": "2.0.3"

**Comment by duxianwei520** [comment]
@Ovilia 妹砸，"echarts": "^4.2.0-rc.2","echarts-liquidfill": "2.0.3"，拷贝node包到内网环境，还是会报components series.liquidFill not exists，好尴尬

**Comment by Ovilia** [comment]
@duxianwei520 `console.log(echarts.version)` 是多少

**Comment by ITdian** [comment]
@Ovilia `vue项目的main.js中import echarts from 'Echarts'
Vue.prototype.$_df_echarts = echarts
import 'echarts-liquidfill''package中依赖为   
   "echarts": "^4.2.1",
    "echarts-liquidfill": "^2.0.5",
    "zrender": "^4.0.7"`
使用npm ls 确认过版本依赖包正确
还是报错Error: Component series.liquidFill not exists. Load it first.有什么比较好的解决办法么?

**Comment by Ovilia** [comment]
可能是引入了多个 ECharts 版本？
先把 npm 中的 ECharts 移除了，然后 https://github.com/ecomfe/echarts-liquidfill#install-echarts-liquidfill-with-npm

**Comment by ITdian** [comment]
@Ovilia Thanks!是由于import echarts from 'Echarts'  的 Echarts 大写的问题,改成import echarts from 'echarts'即可。之前没有使用到 echarts-liquidfill这样用没有问题的。
