### ISSUE TITLE
关于IE8兼容性问题

### ISSUE THREAD

**Issue by Liumintao** [ecomfe/echarts-liquidfill#73]
我用liquidfill  1.0 +echarts 2.0 在IE8里测试发现图形有问题，并报
Method `dispose` should be implemented in liquidFill.
请问该如何解决该问题，谢谢！

**Comment by Ovilia** [comment]
报错截图麻烦提供下，请使用未压缩版本的 ECharts 以便我们定位问题

**Comment by Liumintao** [comment]
liquidfill 1.0 +echarts 2.0，是不是要用最新版的echarts的IE兼容版本？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 羡辙 <notifications@github.com>
发送时间: Saturday, November 17, 2018 12:59:01 PM
收件人: ecomfe/echarts-liquidfill
抄送: Liumintao; Author
主题: Re: [ecomfe/echarts-liquidfill] 关于IE8兼容性问题 (#73)


报错截图麻烦提供下，请使用未压缩版本的 ECharts 以便我们定位问题

―

**Comment by Ovilia** [comment]
https://github.com/ecomfe/echarts-liquidfill/blob/master/package.json#L13 有写最低 ECharts 版本要求是 4.1.0，IE 8 不知道 clipPath 有没有问题，你可以试一下~
