### ISSUE TITLE
水球图配合echarts4的dataset可以实现么，该如何实现呢？

### ISSUE THREAD

**Issue by sashangli** [ecomfe/echarts-liquidfill#75]

**Comment by Ovilia** [comment]
水球图暂不支持，其实水球图的数据都特别简单，有什么特别的需求需要 dataset 吗？

**Comment by sashangli** [comment]
也没啥，最近在做一个基于echarts的图表可视化配置系统，我考虑用dataset来进行统一的数据管理，所以问问，不支持就只能单独处理了。
