### ISSUE TITLE
使用官网的例子，如果调用resize,如果由小放大，样式错误

### ISSUE THREAD

**Issue by itcongaili** [ecomfe/echarts-liquidfill#76]
使用的官网的例子，一开始用很小的窗口打开如下图

![default](https://user-images.githubusercontent.com/11898652/50582337-c7209880-0e9c-11e9-976b-846bac616e46.png)
然后按下F11最大浏览器窗口下显示 如下图，显示异常
![default](https://user-images.githubusercontent.com/11898652/50582348-de5f8600-0e9c-11e9-9af2-16c5d0331502.png)
希望一个解决办法，谢谢！

**Comment by Ovilia** [comment]
已修复，请使用 2.0.4 版本

**Comment by itcongaili** [comment]
谢谢 @Ovilia
