### ISSUE TITLE
当 shape设置为 rect 时，水波不能填满整个矩形容器

### ISSUE THREAD

**Issue by KevinCN511** [ecomfe/echarts-liquidfill#8]
设置如下：
```
shape: 'rect',
radius: '100%'
```
程序按长方形容器的高，生成正方形图形，如何设置可以填满整个长方形容器？

**Comment by Ovilia** [comment]
把 `outline` 的 `borderDistance` 设为 0：

```js
var option = {
    series: [{
        type: 'liquidFill',
        radius: '80%',
        data: [0.5, 0.45, 0.4, 0.3],
        shape: 'rect',
        outline: {
            borderDistance: 0
        }
    }]
};
```

http://gallery.echartsjs.com/editor.html?c=xrymUNiO3e&v=1

**Comment by KevinCN511** [comment]
Thanks Ovilia, 但并没有解决我的问题，如你提供的示例，显示的波纹仍是绘制在一个正方形中，我想要的是一个长方形

**Comment by Ovilia** [comment]
哦懂了~ 那确实没法实现，现在会按“保持长宽比例的情况下，按短的约束作为长度”

**Comment by KevinCN511** [comment]
我通过 sharpe: 'path://' 方法，并修改了 getPath 中的一些算法，暂时实现了我的需求。还是希望作者能将这个功能完善，这样这个插件的使用范围会更广一些。

**Comment by MichaelIT** [comment]
@KevinCN511 能分享一下吗？

**Comment by Ovilia** [comment]
目前支持将 `shape` 设为 `'container'` 实现该效果，参考例子：https://github.com/ecomfe/echarts-liquidfill/blob/master/example/fill-container.html

**Comment by ly1508999190** [comment]
为何 柱形图这些能 实现 这种非保持长宽比例的？而水波图却不行呢。

**Comment by ly1508999190** [comment]
这样很坑啊
![image](https://user-images.githubusercontent.com/12368299/52945191-20407f00-33ac-11e9-9296-a28db6d58bfc.png)

**Comment by Ovilia** [comment]
@ly1508999190 https://github.com/ecomfe/echarts-liquidfill/blob/master/example/fill-container.html#L65 这个设置可以
