### ISSUE TITLE
水球图显示问题

### ISSUE THREAD

**Issue by chenxiaoleizi** [ecomfe/echarts-liquidfill#83]
配置如下
```js
var option = {
    series: [{
        type: 'liquidFill',
        data: [0.6]
    }]
};
```
结果如图
![qq 20190122133600](https://user-images.githubusercontent.com/24647177/51514612-74a71c00-1e4b-11e9-8eff-45228e971c28.png)

**Comment by Ovilia** [comment]
这个……容器多大？

**Comment by chenxiaoleizi** [comment]
48*48px的，是因为容器太小吗？

**Comment by Ovilia** [comment]
是的，或者把其他参数调整下（比如字号，半径调成50%之类的）
