### ISSUE TITLE
[feature request] add yAxis support

### ISSUE THREAD

**Issue by lianzhao** [ecomfe/echarts-liquidfill#84]
I want to implement something like this
![image](https://user-images.githubusercontent.com/536786/51849346-70529580-235a-11e9-8e70-00d741cbb9ed.png)

Currently I have done everything but the yAxis... Any workarounds?
![image](https://user-images.githubusercontent.com/536786/51849504-d5a68680-235a-11e9-86f7-85309d48437f.png)

**Comment by Ovilia** [comment]
ECharts series can work together, so you can just add a bar series without data to make the axis.

**Comment by lianzhao** [comment]
> so you can just add a bar series without data to make the axis.

OK, I will try to add a bar chart with invisible bars...

> Are them images or the circles have moving animations?

The 'bubbles' are `echarts.graphic.Circle`s, they have animations and they are clipping with the waves:)

**Comment by Ovilia** [comment]
Cool!

**Comment by Unremittingly** [comment]
我也想要y轴啊，类似于这种
![image](https://user-images.githubusercontent.com/24286827/59010859-56bfde00-8865-11e9-967a-af71bbcaf47f.png)

**Comment by Ovilia** [comment]
@Unremittingly This can be achieved by adding another `grid` component and add `xAxis` with `show: false` and `yAxis` with `show: true`.
