### ISSUE TITLE
设置渐变报错

### ISSUE THREAD

**Issue by September-xx** [ecomfe/echarts-liquidfill#89]
版本 
"echarts": "^4.2.1",
 "echarts-liquidfill": "^2.0.4",

series:[{
    data:[0.6],
     color:[{
            type: 'linear',
            x: 0,
            y: 0,
            x2: 0,
            y2: 1,
            colorStops: [{ //填充区渐变色
                offset: 0,
                color: '#f898b3'
            }, {
                offset: 0.2,
                color: '#fac8d3'
            }, {
                offset: 1,
                color: '#ffffff'
            }]
    }]
}]

设置渐变 循环报错 Style.js?0c24:445 Uncaught TypeError: Failed to execute 'addColorStop' on 'CanvasGradient': The provided float value is non-finite.

**Comment by September-xx** [comment]
求大神支招

**Comment by chenmo00000** [comment]
同样的问题，我感觉无解，除非版本更新

**Comment by Ovilia** [comment]
@chenmo00000 能提供一个例子吗？上面的例子我用 echarts-liquidfill 2.0.5，echarts 4.8.0 测了没问题。
