### ISSUE TITLE
 渐变色报错，Failed to execute 'addColorStop' on 'CanvasGradient'

### ISSUE THREAD

**Issue by September-xx** [ecomfe/echarts-liquidfill#90]
"echarts": "4.1.0",
"echarts-liquidfill": "2.0.1"

@Ovilia 在线呼叫小姐姐求帮助  使用渐变色报错   Uncaught TypeError: Failed to execute 'addColorStop' on 'CanvasGradient': The provided float value is non-finite.

参考了很多issue，试了好几个版本都不行，依然会报错。 node_modules 也是删掉重新安装的 日然会有问题。
#50  参考了这个issue  目前版本号是是4.1.0  和 2.0.1

**Comment by September-xx** [comment]
"echarts": "4.1.0",
"echarts-liquidfill": "2.0.1"   
这两个版本可以的 但是使用渐变又会出现颜色不更新 参考 #58解决后又会报  ailed to execute 'addColorStop错误...... 请问该怎么解决   新版本貌似也会有问题

**Comment by Ovilia** [comment]
是 SVG 吗？

**Comment by September-xx** [comment]
> 是 SVG 吗？

@Ovilia  是  canvas  ，不好意思之前几天没看到回复

**Comment by September-xx** [comment]
SVG 也会报错 gradient.colorStops  NaN

**Comment by September-xx** [comment]
@Ovilia 参考了  echarts 7569 issue   https://github.com/apache/incubator-echarts/issues/7569  只能禁止动画或者重新clear才正常渐变渲染   但是这样效果都不符合预期  有什么比较好的解决办法吗

**Comment by Ovilia** [comment]
是的，动画没法支持插值。没有更好的办法，出发你提个颜色插值的 PR？其实情况很复杂，不太好搞……
