### ISSUE TITLE
i can't change fontSize

### ISSUE THREAD

**Issue by yanglimou** [ecomfe/echarts-liquidfill#91]
{
        title: {
            text: null,
        },
        series: [{
            type: 'liquidFill',
            radius: '70%',
            data: data,
            backgroundStyle: {
                borderWidth: 5,
                borderColor: '#76b9ed',
                color: 'rgba(255,0,255,0)'
            },
            label: {
                **fontSize: 30,**
                normal: {
                    formatter: value * 100 + '%',
                }
            }
        }]
    }

**Comment by PatrickNgZh** [comment]
I also encountered this problem. you are supposed to switch to 3.x.x version.

**Comment by Ovilia** [comment]
It works with echarts 4.2.1 and echarts-liquidFill 2.0.4. 
If it still not works for you, please use the latest version and provide the version code here.
