### ISSUE TITLE
liquidFillView.js  283行的console麻烦删一下吧  看着很难受

### ISSUE THREAD

**Issue by liuxiaoxin123** [ecomfe/echarts-liquidfill#93]
console.log(radiusY);

**Comment by Ovilia** [comment]
https://github.com/ecomfe/echarts-liquidfill/commit/58551bd547a5210b478a5fd84f45f7333d11f2dc
之前已经删了

**Comment by morris821028** [comment]
I think it will be released at v2.0.5 bugfix, right?

**Comment by Ovilia** [comment]
@morris821028 Yes. I released it a moment ago.
