### ISSUE TITLE
使用了这段代码来设置折线图上的小圆点的颜色，然后就一直报这个错误

### ISSUE THREAD

**Issue by XdYangXiaoRong** [ecomfe/echarts-liquidfill#94]
itemStyle: {
              normal:{
                // color: "rgb(242,184,0)",//线上小圆点的颜色
                color: {
                    type: 'radial',
                    x: 0.5,
                    y: 0.5,
                    r: 0.4,
                    colorStops: [{
                        offset: 0.4, color: 'rgb(242,184,0)' // 0% 处的颜色
                    }, {
                        offset: 1, color: 'rgba(242,184,0,0.5)' // 100% 处的颜色
                    }],
                    global: false // 缺省为 false
                }
              }
            },
使用了这段代码来设置折线图上的小圆点的颜色，然后就一直报这个错误Maximum call stack size exceeded;at App onError function;at setTimeout callback function
RangeError: Maximum call stack size exceeded

**Comment by Ovilia** [comment]
测试了 2.0.5 版本，ECharts 4.8.0，没有复现。
