### ISSUE TITLE
请问如何取消水波上的黑色阴影？

### ISSUE THREAD

**Issue by jackfromcumt** [ecomfe/echarts-liquidfill#96]
请问如何取消水波上的黑色阴影？

**Comment by Ovilia** [comment]
`shadowBlur` 设为 0，参见 https://github.com/ecomfe/echarts-liquidfill#shadow

**Comment by jackfromcumt** [comment]
> `shadowBlur` 设为 0，参见 https://github.com/ecomfe/echarts-liquidfill#shadow

这个只能取消外环的阴影。水波上面的阴影好像无法去掉

**Comment by Ovilia** [comment]
水波上的阴影是 `itemStyle.shadowBlur`

**Comment by Shideshanxx** [comment]
解决了吗

**Comment by Shideshanxx** [comment]
npm引入可以取消阴影，cdn引入设置无效

**Comment by jackfromcumt** [comment]
> 解决了吗

解决了，按照itemStyle.shadowBlur设置的
