### ISSUE TITLE
label.position为数组时在svg下报错

### ISSUE THREAD

**Issue by ChuChencheng** [ecomfe/echarts-liquidfill#98]
### Version

echarts 4.2.1
echarts-liquidfill 2.0.5

### Reproduction link

https://jsfiddle.net/e9Loum7r/

### Description

1. label.position 为数组时在 svg 下报错，无法正常渲染 label
2. 另外，label.position 为字符串时，除了 `inside` ， 其他选项在 svg 下与 canvas 表现不一致

**Comment by Ovilia** [comment]
echarts 4.8.0, echarts-liquidfill 2.0.6 没有复现出 position 数组的问题。
svg 位置和 canvas 略有不同是两种渲染引擎文字排版的误差，没有很大影响。
